name: cer
channels:
  - conda-forge
  - defaults
dependencies:
  # Replaces pip
  - poetry

  # Wrangling
  - dask
  
  # File operations
  - pyarrow
  - openpyxl
  - xlrd

  # dev
  - pytest
  - black
  